timestamp() function change
There was an error in the Auto.py file. The timestamp() function at line number 123.
Error was as follows:
Traceback (most recent call last):
File "Auto.py", line 123, in
temp = curmeeting[0].timestamp()
AttributeError: 'str' object has no attribute 'timestamp'

I have edited the method to get the time-stamp and now it should work fine. I have already tested it.
Now, there's even no need to change the cell format of the Excel file :)